Numpy refers to Numurical Python

In [1]:
import numpy as np

In [2]:
from time import process_time

In [4]:
python_list = [i for i in range(1000)]
start_time = process_time()

python_list = [i+5 for i in range(1000)]
end_time = process_time()

print(end_time - start_time)

0.00022329000000009813


In [5]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()

np_array+=5
end_time = process_time()

print(end_time - start_time)

0.0008767700000000822


Numpy Arrays

In [7]:
#List
listdata = [1,2,3,4,5]
print(listdata)
type(listdata)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [9]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [10]:
b = np.array([(1,2,3,4),(4,5,6,7)])
b.shape

(2, 4)

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
#Create an identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.randint(10,100,(2,4))

array([[93, 94, 69, 90],
       [20, 51, 74, 28]])

In [16]:
list2 = [3,5,55,66]
np.array(list2)

array([ 3,  5, 55, 66])

In [17]:
c = np.random.randint(10,89,(4,4))
c

array([[39, 33, 50, 22],
       [55, 18, 84, 17],
       [33, 29, 10, 43],
       [68, 37, 64, 32]])

In [18]:
c.shape

(4, 4)

In [19]:
c.ndim

2

In [20]:
c.size

16

Mathematical Operation of Numpy Array

In [22]:
a = np.random.randint(10,20,(5,5))
b = np.random.randint(40,80,(5,5))

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[80 73 55 71 59]
 [83 78 66 71 80]
 [51 68 69 63 80]
 [86 65 79 86 73]
 [69 78 74 81 75]]
[[-54 -43 -29 -49 -37]
 [-47 -52 -38 -49 -58]
 [-31 -38 -45 -27 -54]
 [-64 -43 -47 -56 -37]
 [-39 -58 -38 -47 -53]]
[[ 871  870  546  660  528]
 [1170  845  728  660  759]
 [ 410  795  684  810  871]
 [ 825  594 1008 1065  990]
 [ 810  680 1008 1088  704]]
[[0.19402985 0.25862069 0.30952381 0.18333333 0.22916667]
 [0.27692308 0.2        0.26923077 0.18333333 0.15942029]
 [0.24390244 0.28301887 0.21052632 0.4        0.19402985]
 [0.14666667 0.2037037  0.25396825 0.21126761 0.32727273]
 [0.27777778 0.14705882 0.32142857 0.265625   0.171875  ]]


Array Manipulation

In [23]:
np_array = np.random.randint(1,100,(4,4))
np_array

array([[35, 53, 21, 88],
       [58, 74, 17, 60],
       [34, 65, 85, 78],
       [12,  7, 41, 61]])

In [24]:
np.transpose(np_array)

array([[35, 58, 34, 12],
       [53, 74, 65,  7],
       [21, 17, 85, 41],
       [88, 60, 78, 61]])

In [27]:
#Reshape Array

np_array.reshape(8,2)

array([[35, 53],
       [21, 88],
       [58, 74],
       [17, 60],
       [34, 65],
       [85, 78],
       [12,  7],
       [41, 61]])

# **The End**